// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TomatoTime.Data;

#nullable disable

namespace TomatoTime.Migrations
{
    [DbContext(typeof(TomatoTimeDbContext))]
    partial class TomatoTimeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TomatoTime.Data.Entities.SettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BellVolume")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LongBreakInterval")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LongBreakMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("OverlayOpacity")
                        .HasColumnType("REAL");

                    b.Property<bool>("RestoreOnStartup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShortBreakMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StartWithWindows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BellVolume = 70,
                            LongBreakInterval = 4,
                            LongBreakMinutes = 15,
                            OverlayOpacity = 0.69999999999999996,
                            RestoreOnStartup = true,
                            ShortBreakMinutes = 5,
                            StartWithWindows = false,
                            WorkMinutes = 25
                        });
                });

            modelBuilder.Entity("TomatoTime.Data.Entities.TaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TomatoTime.Data.Entities.WorkSessionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("WorkSessions");
                });

            modelBuilder.Entity("TomatoTime.Data.Entities.WorkSessionEntity", b =>
                {
                    b.HasOne("TomatoTime.Data.Entities.TaskEntity", "Task")
                        .WithMany("WorkSessions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TomatoTime.Data.Entities.TaskEntity", b =>
                {
                    b.Navigation("WorkSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
